use_frameworks!

platform :ios, '9.0'

target 'Adaptor_Example' do
  pod 'Adaptor', :path => '../'
  
  pod 'SnapKit'

  target 'Adaptor_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
